
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int EXEC = 26;
  public static final int ESTADISTICO = 19;
  public static final int GUION = 14;
  public static final int PARDE = 6;
  public static final int MENOR = 13;
  public static final int OPERACION = 8;
  public static final int CADENA = 33;
  public static final int PYC = 4;
  public static final int ARR = 16;
  public static final int IGUAL = 22;
  public static final int DECIMAL = 32;
  public static final int COLUMN = 23;
  public static final int END = 3;
  public static final int LLIZ = 17;
  public static final int CONSOLE = 20;
  public static final int PARIZ = 5;
  public static final int DOSP = 11;
  public static final int ID = 12;
  public static final int PROGRAM = 2;
  public static final int TIPO = 9;
  public static final int COMA = 7;
  public static final int MAYOR = 24;
  public static final int LLDER = 18;
  public static final int EOF = 0;
  public static final int VALUES = 29;
  public static final int PRINT = 21;
  public static final int error = 1;
  public static final int ENTERO = 31;
  public static final int EJE = 30;
  public static final int ARROBA = 15;
  public static final int TITULO = 27;
  public static final int TIPOGRAPH = 25;
  public static final int LABEL = 28;
  public static final int VAR = 10;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PROGRAM",
  "END",
  "PYC",
  "PARIZ",
  "PARDE",
  "COMA",
  "OPERACION",
  "TIPO",
  "VAR",
  "DOSP",
  "ID",
  "MENOR",
  "GUION",
  "ARROBA",
  "ARR",
  "LLIZ",
  "LLDER",
  "ESTADISTICO",
  "CONSOLE",
  "PRINT",
  "IGUAL",
  "COLUMN",
  "MAYOR",
  "TIPOGRAPH",
  "EXEC",
  "TITULO",
  "LABEL",
  "VALUES",
  "EJE",
  "ENTERO",
  "DECIMAL",
  "CADENA"
  };
}

